name    'puppet-cfme'
version '0.1'
source 'git://github.com/aweiteka/puppet-cfme.git'
author 'Aaron Weitekamp <aweiteka@redhat.com>'
license 'Apache License, Version 2.0'
summary 'Puppet installer and environment setup for CFME from upstream source'
description 'This module installs CFME from source, installs development tools and sets up development environment.'
project_page 'https://github.com/aweiteka/puppet-cfme'
dependency ''
